name: Build and Push Docker with Branding

on:
  push:
    branches:
      - beta

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - uses: actions/checkout@v4

      # 2️⃣ Set up Python to run branding script
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3️⃣ Run branding script
      - name: Run Rebrand Script
        run: python scripts/branding.py

      # 4️⃣ Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag vocard-dashboard:latest

      # 5️⃣ Log in to GitHub Container Registry
      - name: Log in to GitHub Docker Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 6️⃣ Push the Docker image
      - name: Push the Docker image
        run: |
          docker tag vocard-dashboard:latest ghcr.io/chocomeow/vocard-dashboard:latest
          docker push ghcr.io/chocomeow/vocard-dashboard:latest
